# Generated by Django 4.2.25 on 2025-11-04 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('Build', 'Build'), ('Break', 'Break')], default='Build', max_length=5),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
