# Generated by Django 4.2.25 on 2025-11-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_app', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skill',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
