# Generated by Django 4.2.25 on 2025-11-06 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_app', '0005_skill_level_skill_xp_task_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='frequency',
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Skill_Progress',
        ),
    ]
