# Generated by Django 4.2.25 on 2025-11-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_app', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOTSTARTED', 'Not Started'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=15),
        ),
    ]
