# Generated by Django 4.2.25 on 2025-11-08 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_app', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('habit', 'date')},
        ),
    ]
