# Generated by Django 4.2.25 on 2025-11-21 23:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calibration_app', '0009_alter_journal_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal_type', models.CharField(choices=[('Short Term', 'Short Term'), ('Long Term', 'Long Term'), ('Lifestyle', 'Lifestyle')], default='short_term', max_length=20)),
                ('metric', models.CharField(blank=True, max_length=100, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(default=0)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reflection', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.date.today)),
                ('account_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField()),
                ('mood_type', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('tired', 'Tired'), ('motivated', 'Motivated'), ('neutral', 'Neutral')], max_length=30, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('social_interaction', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.date.today)),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration_app.goals')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration_app.goals'),
        ),
        migrations.AddField(
            model_name='task',
            name='moods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration_app.mood'),
        ),
    ]
