# Generated by Django 4.2.25 on 2025-11-21 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_app', '0010_goals_mood_task_goals_task_moods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='moods',
        ),
    ]
