# Generated by Django 4.2.25 on 2025-11-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_app', '0011_remove_task_moods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to='calibration_app.habit'),
        ),
        migrations.AddField(
            model_name='goals',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='calibration_app.skill'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_type',
            field=models.CharField(choices=[('Short Term', 'Short Term'), ('Long Term', 'Long Term'), ('Lifestyle', 'Lifestyle')], default='Short Term', max_length=20),
        ),
    ]
