# Generated by Django 4.2.25 on 2025-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_app', '0012_goals_habit_goals_skill_alter_goals_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='current_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
