# Generated by Django 4.2.25 on 2025-11-22 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_app', '0013_alter_goals_current_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration_app.habit'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration_app.skill'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
