# Generated by Django 4.2.25 on 2025-11-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_app', '0014_alter_goals_habit_alter_goals_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration_app.habit'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration_app.skill'),
        ),
    ]
