# Generated by Django 4.2.25 on 2025-11-30 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_app', '0019_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
