# Generated by Django 4.2.25 on 2025-12-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_app', '0027_userblock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userblock',
            new_name='calibration_blocker_1aecc3_idx',
            old_name='calibratio_blocker_dd4c85_idx',
        ),
        migrations.AlterField(
            model_name='userblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
